Adjust font stack and fix italics
w3c/clreq pull request #461
Opened 2022-05-03 13:53 UTC by huijing

Closes https://github.com/w3c/clreq/issues/408

This PR makes the following changes:

- Adds custom font family for double and single quote marks for both Simplified and Traditional Chinese
- Updates the font stack to have Latin fonts listed first
- Adds the new font family name for Noto
- Adds comment which explains which font family is for which OS
- Resolves the issue of italics in figure captions with a more generic CSS selector than the one raised in https://github.com/w3c/clreq/pull/459

2022-05-03 14:55 UTC, kecrily requested changes

2022-05-03 14:55 UTC, kecrily commented on local.css
> +}
```suggestion
span:lang(zh) {
  font-style: normal;
}
```

2022-05-19 10:17 UTC, xfq commented
Related discussions: https://www.w3.org/2022/05/17-clreq-minutes.html#t04

2022-05-24 02:46 UTC, huijing commented
@xfq I think this can be merged now.

2022-05-25 01:04 UTC, xfq approved these changes
LGTM. Thank you!

2022-05-25 01:05 UTC, merged

2022-05-25 01:05 UTC, xfq commented
Merging.